name: 'TotallyAccurateHoroscopeGenerator'
description: 'Generates a horoscope using ChatGPT'
inputs:
  template-file:  # id of input
    description: 'Path to the post template file to use'
    required: true
  output-path:  # id of input
    description: 'Path to put the output file'
    required: true
  openai-api-key:
    description: 'API key to used when communicating with ChatGPT. If not included this will generate a basic generated horoscope sutable for testing.'
    required: false
runs:
  using: 'node16'
  main: 'main.js'
