// import { writeFile } from 'node:fs/promises';
import { generateHoroscope } from './src/chatgpt.js';
import { Post } from './src/post.js';
import { generatePrompt } from './src/promptgenerator.js';
import log4js from 'log4js';


async function writeHoroscope(path, horoscope) {
  // Format tbd
  await writeFile(path, JSON.stringify(horoscope));
}

async function main() {
  log4js.configure({
    appenders: {
      console: {
        type: 'console'
      }
    },
    categories: {
      default: { appenders: ['console'], level: 'info' }
    }
  });

  let logger = log4js.getLogger()
  logger.log('Starting post creation')

  let post = new Post("autogenerated.md", ".", false)
  await post.create()
  // console.log(await generatePrompt())
  // let horoscope = await generateHoroscope()
}

main()